export const GooglePlacesStyles: Record<string, (provided: any) => any> = {
  container: (provided) => ({
    ...provided,
    display: "block",
    position: "relative",
    boxSizing: "border-box",
  }),
  control: (base) => ({
    ...base,
    display: "flex",
    flexDirection: "row",
    flexWrap: "wrap",
    alignItems: "center",
    width: "100%",
    borderWidth: 1,
    borderColor: "#9b9b9b",
  }),
  valueContainer: (provided) => ({
    ...provided,
    display: "flex",
    flexDirection: "row",
    flexWrap: "wrap",
    alignItems: "center",
  }),
  indicatorsContainer: (provided) => ({
    ...provided,
    display: "flex",
    flexDirection: "row",
    alignItems: "center",
    alignSelf: "stretch",
  }),
  menu: (provided) => ({
    ...provided,
    display: "block",
    fontFamily: "sans-serif",
  }),
  menuList: (provided) => ({
    ...provided,
    display: "block",
    fontFamily: "sans-serif",
  }),
  menuPortal: (base) => ({ ...base, zIndex: 9999 }),
  option: (provided) => ({
    ...provided,
    display: "block",
    fontFamily: "sans-serif",
  }),
  input: (provided) => ({
    ...provided,
    fontFamily: "sans-serif",
    width: "100%",
    height: 40,
    backgroundColor: "#ffffff",
    borderRadius: 5,
    paddingTop: 10,
    display: "inline-flex",
  }),
  placeholder: (provided) => ({
    ...provided,
    fontFamily: "sans-serif",
    color: "grey",
  }),
  singleValue: (provided) => ({ ...provided, fontFamily: "sans-serif" }),
  noOptionsMessage: (provided) => ({
    ...provided,
    display: "block",
    fontFamily: "sans-serif",
  }),
};
