export const GooglePlacesStyles: Record<string, (provided: any, state?: any) => any> = {
  container: (provided) => ({
    ...provided,
    display: "block",
    position: "relative",
    boxSizing: "border-box",
  }),
  control: (base) => ({
    ...base,
    display: "flex",
    flexDirection: "row",
    flexWrap: "wrap",
    alignItems: "center",
    width: "100%",
    height: 48,
    backgroundColor: "#fff",
    border: "1px solid #e2e8f0",
    borderRadius: 12,
    cursor: "pointer",
    boxShadow: "none",
    "&:hover": {
      borderColor: "#cbd5e1",
    },
  }),
  valueContainer: (provided) => ({
    ...provided,
    display: "flex",
    flexDirection: "row",
    flexWrap: "wrap",
    alignItems: "center",
    padding: "0 16px",
  }),
  indicatorsContainer: (provided) => ({
    ...provided,
    display: "flex",
    flexDirection: "row",
    alignItems: "center",
    alignSelf: "stretch",
  }),
  indicatorSeparator: () => ({
    display: "none",
  }),
  dropdownIndicator: (provided) => ({
    ...provided,
    color: "#94a3b8",
    padding: "0 12px 0 0",
  }),
  menu: (provided) => ({
    ...provided,
    display: "block",
    fontFamily: "sans-serif",
    backgroundColor: "#fff",
    border: "1px solid #e2e8f0",
    borderRadius: 12,
    overflow: "hidden",
    marginTop: 4,
    boxShadow: "0 4px 16px rgba(0,0,0,0.1)",
  }),
  menuList: (provided) => ({
    ...provided,
    display: "block",
    fontFamily: "sans-serif",
    padding: 4,
  }),
  menuPortal: (base) => ({ ...base, zIndex: 9999 }),
  option: (provided, state) => ({
    ...provided,
    display: "block",
    fontFamily: "sans-serif",
    fontSize: 14,
    color: "#0f172a",
    backgroundColor: state?.isFocused ? "#f1f5f9" : "transparent",
    borderRadius: 8,
    padding: "10px 12px",
    cursor: "pointer",
    "&:active": {
      backgroundColor: "#e2e8f0",
    },
  }),
  input: (provided) => ({
    ...provided,
    fontFamily: "sans-serif",
    width: "100%",
    color: "#0f172a",
    fontSize: 15,
    display: "inline-flex",
  }),
  placeholder: (provided) => ({
    ...provided,
    fontFamily: "sans-serif",
    color: "#94a3b8",
    fontSize: 15,
  }),
  singleValue: (provided) => ({
    ...provided,
    fontFamily: "sans-serif",
    color: "#0f172a",
    fontSize: 15,
  }),
  noOptionsMessage: (provided) => ({
    ...provided,
    display: "block",
    fontFamily: "sans-serif",
    color: "#94a3b8",
    fontSize: 14,
  }),
};

// Dark theme version for online store pages
export const GooglePlacesStylesDark: Record<string, (provided: any, state?: any) => any> = {
  container: (provided) => ({
    ...provided,
    display: "block",
    position: "relative",
    boxSizing: "border-box",
  }),
  control: (base) => ({
    ...base,
    display: "flex",
    flexDirection: "row",
    flexWrap: "wrap",
    alignItems: "center",
    width: "100%",
    height: 50,
    backgroundColor: "rgba(255,255,255,0.06)",
    border: "1px solid rgba(255,255,255,0.1)",
    borderRadius: 12,
    cursor: "pointer",
    boxShadow: "none",
    "&:hover": {
      borderColor: "rgba(255,255,255,0.2)",
    },
  }),
  valueContainer: (provided) => ({
    ...provided,
    display: "flex",
    flexDirection: "row",
    flexWrap: "wrap",
    alignItems: "center",
    padding: "0 16px",
  }),
  indicatorsContainer: (provided) => ({
    ...provided,
    display: "flex",
    flexDirection: "row",
    alignItems: "center",
    alignSelf: "stretch",
  }),
  indicatorSeparator: () => ({
    display: "none",
  }),
  dropdownIndicator: (provided) => ({
    ...provided,
    color: "rgba(255,255,255,0.3)",
    padding: "0 12px 0 0",
  }),
  menu: (provided) => ({
    ...provided,
    display: "block",
    fontFamily: "sans-serif",
    backgroundColor: "#1a1a2e",
    border: "1px solid rgba(255,255,255,0.1)",
    borderRadius: 12,
    overflow: "hidden",
    marginTop: 4,
    boxShadow: "0 8px 24px rgba(0,0,0,0.4)",
  }),
  menuList: (provided) => ({
    ...provided,
    display: "block",
    fontFamily: "sans-serif",
    padding: 4,
  }),
  menuPortal: (base) => ({ ...base, zIndex: 9999 }),
  option: (provided, state) => ({
    ...provided,
    display: "block",
    fontFamily: "sans-serif",
    fontSize: 14,
    color: "#fff",
    backgroundColor: state?.isFocused ? "rgba(255,255,255,0.08)" : "transparent",
    borderRadius: 8,
    padding: "10px 12px",
    cursor: "pointer",
    "&:active": {
      backgroundColor: "rgba(255,255,255,0.12)",
    },
  }),
  input: (provided) => ({
    ...provided,
    fontFamily: "sans-serif",
    width: "100%",
    color: "#fff",
    fontSize: 15,
    display: "inline-flex",
  }),
  placeholder: (provided) => ({
    ...provided,
    fontFamily: "sans-serif",
    color: "rgba(255,255,255,0.3)",
    fontSize: 15,
  }),
  singleValue: (provided) => ({
    ...provided,
    fontFamily: "sans-serif",
    color: "#fff",
    fontSize: 15,
  }),
  noOptionsMessage: (provided) => ({
    ...provided,
    display: "block",
    fontFamily: "sans-serif",
    color: "rgba(255,255,255,0.4)",
    fontSize: 14,
  }),
};
